"""WebVTT parsing.

The single most important property tested here is cue merging. WebVTT emits a
cue every few seconds, so one thought arrives as several fragments; if those
became chunks, retrieval would be searching a haystack of "yeah, agreed".

`TestTeamsShape` uses the layout Microsoft Teams actually produces — GUID cue
identifiers, `<v Speaker Name>` voice tags, a NOTE header — so "works with Teams
transcripts" is a tested claim rather than an assumption.
"""

import pytest

from app.core.parsing import (
    has_speaker_attribution,
    looks_like_webvtt,
    parse_timestamp,
    parse_webvtt,
    split_speaker,
    title_and_date,
)

TEAMS = """WEBVTT

NOTE Transcript generated by Microsoft Teams

7c1f0a44-3b21-4d59-9f0e-11a2b3c4d5e6/1-0
00:00:01.000 --> 00:00:04.000
<v Priya Raman>Right, let's talk about the pricing decision.</v>

7c1f0a44-3b21-4d59-9f0e-11a2b3c4d5e6/2-0
00:00:04.000 --> 00:00:07.500
<v Priya Raman>I think we agreed to delay it.</v>

7c1f0a44-3b21-4d59-9f0e-11a2b3c4d5e6/3-0
00:00:07.500 --> 00:00:11.000
<v Tom Beckett>We did, until after the launch.</v>
"""

# What a tenant with speaker attribution disabled returns: valid, timestamped,
# and completely anonymous.
UNATTRIBUTED = """WEBVTT

00:00:01.000 --> 00:00:04.000
Right, let's talk about the pricing decision.

00:00:04.000 --> 00:00:07.500
We did, until after the launch.
"""

SRT = "1\n00:00:01,000 --> 00:00:04,000\nAlice: Hello.\n"


class TestValidation:
    def test_accepts_a_teams_transcript(self):
        assert looks_like_webvtt(TEAMS)

    def test_accepts_a_file_whose_header_was_stripped(self):
        assert looks_like_webvtt("00:00:01.000 --> 00:00:04.000\nAlice: Hi.\n")

    def test_tolerates_a_byte_order_mark(self):
        assert looks_like_webvtt("﻿WEBVTT\n\n")

    def test_rejects_subrip(self):
        """Comma before the milliseconds — close enough to be worth rejecting clearly."""
        assert not looks_like_webvtt(SRT)

    @pytest.mark.parametrize("content", ["", "just some notes", '{"segments": []}'])
    def test_rejects_anything_else(self, content):
        assert not looks_like_webvtt(content)


class TestTimestamps:
    @pytest.mark.parametrize(
        ("raw", "expected"),
        [
            ("00:00:01.000", 1000),
            ("01:02:03.250", 3_723_250),
            ("0:00:05.5", 5500),
            ("02:03", 123_000),
            ("00:00:00.000", 0),
        ],
    )
    def test_converts_to_milliseconds(self, raw, expected):
        assert parse_timestamp(raw) == expected

    def test_unparseable_is_zero_not_an_exception(self):
        assert parse_timestamp("not a time") == 0


class TestSpeakers:
    def test_reads_a_voice_tag(self):
        assert split_speaker("<v Priya Raman>Hello.</v>") == ("Priya Raman", "Hello.")

    def test_voice_tag_without_a_closing_tag(self):
        assert split_speaker("<v Dan Okafor>Hello.") == ("Dan Okafor", "Hello.")

    def test_reads_a_colon_prefix(self):
        assert split_speaker("Tom Beckett: Hello.") == ("Tom Beckett", "Hello.")

    def test_a_colon_mid_sentence_is_not_a_speaker(self):
        speaker, text = split_speaker("The point is this: we should wait.")
        assert speaker is None
        assert text.startswith("The point")

    def test_no_label_at_all(self):
        assert split_speaker("Just some words.") == (None, "Just some words.")


class TestTeamsShape:
    def test_merges_consecutive_cues_from_one_speaker(self):
        """Two Priya cues are one turn; Tom starts a new one."""
        result = parse_webvtt(TEAMS)

        assert [t.speaker for t in result.turns] == ["Priya Raman", "Tom Beckett"]
        assert "pricing decision" in result.turns[0].text
        assert "agreed to delay" in result.turns[0].text

    def test_merged_turn_spans_first_start_to_last_end(self):
        result = parse_webvtt(TEAMS)
        assert result.turns[0].time.start_ms == 1000
        assert result.turns[0].time.end_ms == 7500

    def test_guid_cue_identifiers_and_notes_are_skipped(self):
        """Skipped by construction, so identifier conventions never matter."""
        result = parse_webvtt(TEAMS)
        assert len(result.turns) == 2
        assert "7c1f0a44" not in result.turns[0].text
        assert "NOTE" not in result.turns[0].text

    def test_full_display_names_survive_intact(self):
        assert parse_webvtt(TEAMS).turns[0].speaker == "Priya Raman"


class TestGeneralWebVtt:
    def test_unlabelled_cue_continues_the_current_speaker(self):
        content = (
            "WEBVTT\n\n00:00:01.000 --> 00:00:03.000\n<v Alice>First part</v>\n\n"
            "00:00:03.000 --> 00:00:05.000\nand the rest of it.\n"
        )
        result = parse_webvtt(content)
        assert len(result.turns) == 1
        assert result.turns[0].text == "First part and the rest of it."

    def test_a_cue_with_no_payload_is_ignored(self):
        content = "WEBVTT\n\n00:00:01.000 --> 00:00:03.000\n\n"
        assert parse_webvtt(content).turns == []

    def test_header_only_file_yields_no_turns(self):
        assert parse_webvtt("WEBVTT\n").turns == []


class TestSpeakerAttribution:
    def test_detects_a_normal_transcript(self):
        assert has_speaker_attribution(parse_webvtt(TEAMS))

    def test_detects_an_unattributed_transcript(self):
        """A tenant with attribution off produces valid but anonymous output."""
        result = parse_webvtt(UNATTRIBUTED)

        assert len(result.turns) == 1  # all Unknown, so both cues merge
        assert result.turns[0].speaker == "Unknown"
        assert not has_speaker_attribution(result)

    def test_empty_transcript_has_no_attribution(self):
        assert not has_speaker_attribution(parse_webvtt("WEBVTT\n"))


class TestDerivedMetadata:
    def test_participants_are_distinct_and_in_first_spoken_order(self):
        result = parse_webvtt(TEAMS)
        assert result.participants == ["Priya Raman", "Tom Beckett"]

    def test_duration_is_the_last_end_time(self):
        assert parse_webvtt(TEAMS).duration_ms == 11_000

    def test_empty_transcript_has_zero_duration(self):
        assert parse_webvtt("WEBVTT\n").duration_ms == 0


class TestTitleAndDate:
    def test_lifts_an_iso_date_out_of_the_filename(self):
        title, occurred = title_and_date("2026-03-04-pricing-review.vtt")
        assert title == "pricing review"
        assert occurred is not None
        assert (occurred.year, occurred.month, occurred.day) == (2026, 3, 4)

    def test_handles_compact_and_underscored_dates(self):
        assert title_and_date("20260304_standup.vtt")[0] == "standup"
        assert title_and_date("2026_03_04 retro.vtt")[0] == "retro"

    def test_no_date_leaves_the_whole_stem_as_the_title(self):
        title, occurred = title_and_date("weekly-sync.vtt")
        assert title == "weekly sync"
        assert occurred is None

    def test_an_impossible_date_is_treated_as_text(self):
        """2026-13-45 is a filename, not a date."""
        title, occurred = title_and_date("2026-13-45-notes.vtt")
        assert occurred is None
        assert "2026" in title

    def test_a_filename_that_is_only_a_date_still_gets_a_title(self):
        assert title_and_date("2026-03-04.vtt")[0]


class TestNameHeuristic:
    """The "Name:" fallback, for tools that do not use voice tags."""

    @pytest.mark.parametrize(
        "line",
        [
            "Tom Beckett: Hello.",
            "Priya: Hello.",
            "Dr. Sofia Marquez: Hello.",
        ],
    )
    def test_accepts_display_names(self, line):
        assert split_speaker(line)[0] is not None

    @pytest.mark.parametrize(
        "line",
        [
            "The point is this: we should wait.",
            "One thing to note: it slipped.",
            "My concern is: nobody owns it.",
        ],
    )
    def test_rejects_sentence_fragments(self, line):
        """Lowercase words give it away — a display name is capitalised throughout."""
        assert split_speaker(line)[0] is None
