/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness. Deliberately checks nothing — it answers "is the process up".
         *
         *     Kept separate from readiness so an orchestrator restarts a wedged process
         *     without also restarting one that is merely waiting on the database.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness: can this instance actually serve traffic?
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Meetings
         * @description Returns the domain model directly — the wire shape does not differ from it.
         */
        get: operations["list_meetings_meetings_get"];
        put?: never;
        /** Upload Meeting */
        post: operations["upload_meeting_meetings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/{meeting_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Meeting
         * @description Remove a meeting, its turns, its chunks and its extracted facts.
         *
         *     A real delete rather than a flag. A soft delete would have to be honoured by
         *     retrieval, by extraction listings, by the timeline and by the evaluation
         *     harness, and the first place that forgets to filter starts answering
         *     questions out of a transcript the user removed. Given that, the honest thing
         *     is to remove the rows.
         *
         *     Two things deliberately survive. The stored upload file stays on disk, as it
         *     does today for every ingest, because the graph checkpoint still references it
         *     for a resume. And the job record stays readable at `/jobs/{job_id}`, because
         *     it is the history of a run that really happened — its `meeting_id` now points
         *     at nothing, which is accurate.
         */
        delete: operations["delete_meeting_meetings__meeting_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/{meeting_id}/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meeting Facts
         * @description One meeting's decisions, commitments and open threads.
         *
         *     A sub-resource rather than a filter on `/facts`, because that is what it is:
         *     the natural read after opening a meeting, and the shape a detail view asks
         *     for without having to construct a query.
         */
        get: operations["meeting_facts_meetings__meeting_id__facts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Job status, read straight out of the graph checkpoint.
         *
         *     No jobs table: the checkpointer already stores exactly this, keyed by
         *     thread identifier, and duplicating it would just be a second thing to
         *     keep in sync.
         */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Facts
         * @description Facts across the whole corpus.
         *
         *     The cross-meeting view is the point. "What did we commit to" is a question
         *     about a series of meetings, and answering it from a list is both cheaper and
         *     more complete than answering it from retrieval.
         */
        get: operations["search_facts_facts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Chunks
         * @description Retrieval on its own, with no model in the loop.
         *
         *     Exposed as its own endpoint rather than hidden inside chat because retrieval
         *     quality is the thing that decides whether answers are any good, and it can
         *     only be tuned and measured when it is separable from generation.
         *
         *     The response carries per-strategy ranks and per-stage timings so the "how
         *     was this found" panel reads from the same payload the caller already has.
         */
        post: operations["search_chunks_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Stream
         * @description Server-Sent Events rather than a WebSocket.
         *
         *     The traffic is one-directional — the question arrives in this request body,
         *     and everything after is server to client. A WebSocket would add a protocol
         *     upgrade, reconnection handling and sticky-session concerns to buy a direction
         *     that is never used.
         */
        post: operations["chat_stream_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Answer */
        Answer: {
            /** Question */
            question: string;
            /** Text */
            text: string;
            /** Citations */
            citations?: components["schemas"]["AnswerCitation"][];
            /**
             * Refused
             * @default false
             */
            refused: boolean;
            /** Excerpts */
            excerpts?: components["schemas"]["ScoredChunk"][];
            trace: components["schemas"]["AnswerTrace"];
        };
        /**
         * AnswerCitation
         * @description A verified reference. Exists only if the chunk behind it was in context.
         *
         *     Carries the meeting title and speakers directly, so the evidence panel
         *     renders without a request per citation.
         */
        AnswerCitation: {
            /** Marker */
            marker: number;
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Meeting Id
             * Format: uuid
             */
            meeting_id: string;
            /** Meeting Title */
            meeting_title: string;
            /** Speakers */
            speakers: string[];
            time: components["schemas"]["TimeRange"];
            /** Quote */
            quote: string;
        };
        /**
         * AnswerTrace
         * @description What the system did, in the response the caller already has.
         */
        AnswerTrace: {
            /** Search Query */
            search_query: string;
            /**
             * Rewritten
             * @default false
             */
            rewritten: boolean;
            /**
             * Attempts
             * @default 1
             */
            attempts: number;
            /**
             * Hits Considered
             * @default 0
             */
            hits_considered: number;
            /**
             * Sufficient
             * @default true
             */
            sufficient: boolean;
            /** Dropped Markers */
            dropped_markers?: number[];
            /** Timings Ms */
            timings_ms?: {
                [key: string]: number;
            };
            /**
             * Tokens
             * @default 0
             */
            tokens: number;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
        };
        /** Body_upload_meeting_meetings_post */
        Body_upload_meeting_meetings_post: {
            /** File */
            file: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Question */
            question: string;
            /** Meeting Ids */
            meeting_ids?: string[];
            /** Speaker */
            speaker?: string | null;
        };
        /**
         * FactKind
         * @description What extraction pulls out of a meeting.
         *
         *     Three kinds, distinguished by what they commit someone to. A DECISION settles
         *     a question. A COMMITMENT names a person who will do something. An OPEN_THREAD
         *     is a question raised and left unanswered — the one that makes a meeting series
         *     legible, because it is what the next meeting is supposed to close.
         *
         *     Deliberately not a general "topic" or "summary" kind: those cannot be verified
         *     against a specific stretch of transcript, and unverifiable output is what this
         *     system is built to avoid.
         * @enum {string}
         */
        FactKind: "decision" | "commitment" | "open_thread";
        /** FactResponse */
        FactResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Meeting Id
             * Format: uuid
             */
            meeting_id: string;
            /** Meeting Title */
            meeting_title: string;
            kind: components["schemas"]["FactKind"];
            /** Statement */
            statement: string;
            /** Owner */
            owner?: string | null;
            /** Due */
            due?: string | null;
            /** Start Turn Index */
            start_turn_index: number;
            /** End Turn Index */
            end_turn_index: number;
            time: components["schemas"]["TimeRange"];
            /** Speakers */
            speakers?: string[];
            /** Created At */
            created_at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
        };
        /**
         * JobResponse
         * @description A flattened read of the ingestion state.
         *
         *     Differs from `IngestionState` in ways the wire needs: chunk identifiers
         *     collapse to a count, and the per-stage durations are summed. Worth its own
         *     shape rather than exposing the state object, which is an internal contract
         *     that will keep changing as nodes are filled in.
         */
        JobResponse: {
            /** Job Id */
            job_id: string;
            stage: components["schemas"]["Stage"];
            /** Filename */
            filename: string;
            detected_format?: components["schemas"]["TranscriptFormat"] | null;
            /** Meeting Id */
            meeting_id?: string | null;
            /**
             * Turn Count
             * @default 0
             */
            turn_count: number;
            /**
             * Chunk Count
             * @default 0
             */
            chunk_count: number;
            /**
             * Fact Count
             * @default 0
             */
            fact_count: number;
            /**
             * Dropped Fact Count
             * @default 0
             */
            dropped_fact_count: number;
            /**
             * Total Duration Ms
             * @default 0
             */
            total_duration_ms: number;
            /** Stats */
            stats?: {
                [key: string]: components["schemas"]["StageStats"];
            };
            /** Errors */
            errors?: components["schemas"]["StageError"][];
        };
        /** Meeting */
        Meeting: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Title */
            title: string;
            /** Source Filename */
            source_filename: string;
            source_format: components["schemas"]["TranscriptFormat"];
            /** Occurred At */
            occurred_at?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Participants */
            participants?: string[];
            /** Created At */
            created_at?: string | null;
        };
        /** ReadyResponse */
        ReadyResponse: {
            /** Status */
            status: string;
            /** Database */
            database: string;
            /** Migrations */
            migrations: string;
        };
        /**
         * ScoredChunk
         * @description A fused hit hydrated with enough content to be read or cited.
         */
        ScoredChunk: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Meeting Id
             * Format: uuid
             */
            meeting_id: string;
            /** Meeting Title */
            meeting_title: string;
            /** Chunk Index */
            chunk_index: number;
            /** Text */
            text: string;
            time: components["schemas"]["TimeRange"];
            /** Speakers */
            speakers: string[];
            /** Score */
            score: number;
            /** Ranks */
            ranks?: {
                [key: string]: number;
            };
            /** Context Before */
            context_before?: string | null;
            /** Context After */
            context_after?: string | null;
        };
        /** SearchRequest */
        SearchRequest: {
            /** Query */
            query: string;
            /**
             * Limit
             * @default 8
             */
            limit: number;
            /** Meeting Ids */
            meeting_ids?: string[];
            /** Speaker */
            speaker?: string | null;
            /**
             * Expand
             * @default false
             */
            expand: boolean;
        };
        /** SearchResult */
        SearchResult: {
            /** Query */
            query: string;
            /** Hits */
            hits: components["schemas"]["ScoredChunk"][];
            /** Strategy */
            strategy: string;
            /** Candidates */
            candidates?: {
                [key: string]: number;
            };
            /** Timings Ms */
            timings_ms?: {
                [key: string]: number;
            };
        };
        /**
         * Stage
         * @description Where an ingestion job has reached.
         *
         *     Ordered as the pipeline runs. FAILED is terminal and can be entered from
         *     anywhere.
         * @enum {string}
         */
        Stage: "received" | "validated" | "parsed" | "chunked" | "contextualised" | "embedded" | "extracted" | "done" | "failed";
        /** StageError */
        StageError: {
            /** Stage */
            stage: string;
            /** Message */
            message: string;
            /**
             * Recoverable
             * @default false
             */
            recoverable: boolean;
        };
        /**
         * StageStats
         * @description One node's measurements. The cost and latency story is assembled from these.
         */
        StageStats: {
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
            /**
             * Items In
             * @default 0
             */
            items_in: number;
            /**
             * Items Out
             * @default 0
             */
            items_out: number;
            /**
             * Tokens
             * @default 0
             */
            tokens: number;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
        };
        /**
         * TimeRange
         * @description Offset from the start of the recording, in milliseconds.
         *
         *     Milliseconds rather than a timedelta because that is what every transcript
         *     format gives us and what the user interface needs back for seeking.
         */
        TimeRange: {
            /** Start Ms */
            start_ms: number;
            /** End Ms */
            end_ms: number;
        };
        /**
         * TranscriptFormat
         * @description Formats accepted at ingest.
         *
         *     One member, on purpose. WebVTT is what Teams exports and what most
         *     transcription tooling emits; supporting it completely is worth more than
         *     supporting several formats adequately. The enum stays rather than being
         *     replaced with a hardcoded string so the stored `source_format` keeps meaning
         *     when a second format is added.
         * @enum {string}
         */
        TranscriptFormat: "webvtt";
        /** UploadAccepted */
        UploadAccepted: {
            /** Job Id */
            job_id: string;
            /** Filename */
            filename: string;
            /** Status Url */
            status_url: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    list_meetings_meetings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"][];
                };
            };
        };
    };
    upload_meeting_meetings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_meeting_meetings_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_meeting_meetings__meeting_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meeting_facts_meetings__meeting_id__facts_get: {
        parameters: {
            query?: {
                kind?: components["schemas"]["FactKind"] | null;
            };
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_facts_facts_get: {
        parameters: {
            query?: {
                kind?: components["schemas"]["FactKind"] | null;
                owner?: string | null;
                meeting_id?: string[] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_chunks_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Answer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
