"""Ingestion end to end, against a real database.

Scope is WebVTT only. Embedding degrades to a recorded warning when no API key
is configured, so this suite runs — and the product remains usable through
keyword search — without one.
"""

import asyncio

import pytest

TEAMS = b"""WEBVTT

NOTE Transcript generated by Microsoft Teams

7c1f0a44-3b21-4d59-9f0e-11a2b3c4d5e6/1-0
00:00:01.000 --> 00:00:06.000
<v Priya Raman>Right, let's start with the pricing decision.</v>

7c1f0a44-3b21-4d59-9f0e-11a2b3c4d5e6/2-0
00:00:06.000 --> 00:00:11.000
<v Priya Raman>I still think we should hold it until after launch.</v>

7c1f0a44-3b21-4d59-9f0e-11a2b3c4d5e6/3-0
00:00:11.000 --> 00:00:18.000
<v Tom Beckett>Agreed. Let's revisit in the next planning session.</v>
"""

UNATTRIBUTED = b"""WEBVTT

00:00:01.000 --> 00:00:06.000
Right, let's start with the pricing decision.

00:00:06.000 --> 00:00:11.000
Agreed, let's revisit next time.
"""

pytestmark = pytest.mark.integration


async def _wait(client, job_id: str, timeout: float = 30.0) -> dict:
    deadline = asyncio.get_event_loop().time() + timeout
    last: dict = {}
    while asyncio.get_event_loop().time() < deadline:
        response = await client.get(f"/jobs/{job_id}")
        if response.status_code == 200:
            last = response.json()
            if last["stage"] in {"done", "failed"}:
                return last
        await asyncio.sleep(0.1)
    return last


async def _ingest(client, name: str, payload: bytes) -> dict:
    response = await client.post("/meetings", files={"file": (name, payload, "text/vtt")})
    assert response.status_code == 202
    return await _wait(client, response.json()["job_id"])


class TestHealth:
    async def test_health_needs_nothing(self, client):
        assert (await client.get("/health")).json()["status"] == "ok"

    async def test_ready_reports_the_applied_migration(self, client):
        body = (await client.get("/ready")).json()
        assert body["database"] == "ok"
        assert body["migrations"] != "none"


class TestIngestion:
    async def test_a_teams_transcript_runs_to_completion(self, client):
        job = await _ingest(client, "2026-03-04-planning.vtt", TEAMS)

        assert job["stage"] == "done"
        assert job["detected_format"] == "webvtt"
        assert job["meeting_id"] is not None
        # Two turns from three cues: Priya's consecutive cues merge.
        assert job["turn_count"] == 2
        assert job["chunk_count"] >= 1

    async def test_every_node_records_its_own_timing(self, client):
        """Guards the reducer: without a merge, only the last node's stats survive."""
        job = await _ingest(client, "planning.vtt", TEAMS)

        assert {"validate", "parse", "chunk", "contextualise", "embed"} <= set(job["stats"])

    async def test_chunk_stats_report_turns_in_and_chunks_out(self, client):
        job = await _ingest(client, "planning.vtt", TEAMS)
        assert job["stats"]["chunk"]["items_in"] == job["turn_count"]
        assert job["stats"]["chunk"]["items_out"] == job["chunk_count"]

    async def test_meeting_records_participants_duration_and_date(self, client):
        await _ingest(client, "2026-03-04-planning.vtt", TEAMS)

        listing = (await client.get("/meetings")).json()
        meeting = next(m for m in listing if m["source_filename"] == "2026-03-04-planning.vtt")
        assert sorted(meeting["participants"]) == ["Priya Raman", "Tom Beckett"]
        assert meeting["duration_ms"] == 18_000
        assert meeting["occurred_at"].startswith("2026-03-04")
        assert meeting["title"] == "planning"


class TestScopeRejection:
    async def test_a_non_webvtt_file_fails_with_a_useful_message(self, client):
        """Scoped software says what it wants; broken software throws a parse error."""
        job = await _ingest(client, "notes.txt", b"Alice: some plain text notes\n")

        assert job["stage"] == "failed"
        assert job["stats"].keys() == {"validate", "finalise"}  # stopped immediately
        assert "Download" in job["errors"][0]["message"]

    async def test_subrip_is_rejected_rather_than_half_parsed(self, client):
        job = await _ingest(client, "x.srt", b"1\n00:00:01,000 --> 00:00:04,000\nAlice: Hi.\n")
        assert job["stage"] == "failed"

    async def test_valid_webvtt_with_no_cues_fails_at_parse_not_validate(self, client):
        """A different problem from the wrong format, and reported as one."""
        job = await _ingest(client, "empty.vtt", b"WEBVTT\n\n")

        assert job["stage"] == "failed"
        assert "parse" in job["stats"]
        assert "no cues" in job["errors"][0]["message"]


class TestDegradation:
    async def test_missing_speaker_attribution_is_a_recorded_warning(self, client):
        """Teams tenants can disable attribution; the file is valid but anonymous."""
        job = await _ingest(client, "anon.vtt", UNATTRIBUTED)

        assert job["stage"] == "done"
        assert any("speaker" in e["message"] and e["recoverable"] for e in job["errors"])

    async def test_missing_api_key_is_a_recorded_warning_not_a_crash(self, client):
        from app.config import get_settings

        if get_settings().openai_api_key:
            pytest.skip("a key is configured, so embedding is not skipped")

        job = await _ingest(client, "planning.vtt", TEAMS)

        assert job["stage"] == "done"
        assert job["chunk_count"] >= 1
        assert any(e["stage"] == "embed" and e["recoverable"] for e in job["errors"])


class TestErrors:
    async def test_unknown_job_is_a_404(self, client):
        response = await client.get("/jobs/00000000-0000-0000-0000-000000000000")
        assert response.status_code == 404

    async def test_empty_upload_is_rejected(self, client):
        response = await client.post("/meetings", files={"file": ("e.vtt", b"", "text/vtt")})
        assert response.status_code == 400
