"""Initial schema: meetings, turns, chunks.

Hand-written rather than autogenerated — the vector column, the generated
tsvector column and the vector index all need dialect-specific SQL that
autogenerate does not produce cleanly.

The facts tables (decisions, action items) deliberately wait for a later
migration. Adding them now, unused, would be guessing at their shape before
the extraction pass exists to constrain it.

Revision ID: 0001
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import TSVECTOR
from sqlalchemy.dialects.postgresql import UUID as PGUUID

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

EMBEDDING_DIMENSIONS = 1536  # text-embedding-3-small


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "meetings",
        sa.Column("id", PGUUID(as_uuid=True), primary_key=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("source_filename", sa.Text(), nullable=False),
        sa.Column("source_format", sa.String(16), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("participants", sa.ARRAY(sa.Text()), nullable=False, server_default="{}"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )

    op.create_table(
        "turns",
        sa.Column("id", PGUUID(as_uuid=True), primary_key=True),
        sa.Column(
            "meeting_id",
            PGUUID(as_uuid=True),
            sa.ForeignKey("meetings.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("turn_index", sa.Integer(), nullable=False),
        sa.Column("speaker", sa.Text(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.UniqueConstraint("meeting_id", "turn_index", name="uq_turns_meeting_index"),
    )
    op.create_index("ix_turns_meeting_id", "turns", ["meeting_id"])

    op.create_table(
        "chunks",
        sa.Column("id", PGUUID(as_uuid=True), primary_key=True),
        sa.Column(
            "meeting_id",
            PGUUID(as_uuid=True),
            sa.ForeignKey("meetings.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("start_turn_index", sa.Integer(), nullable=False),
        sa.Column("end_turn_index", sa.Integer(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("speakers", sa.ARRAY(sa.Text()), nullable=False, server_default="{}"),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("context_header", sa.Text(), nullable=True),
        sa.Column("embedding", sa.dialects.postgresql.ARRAY(sa.Float), nullable=True),
        sa.Column(
            "text_search",
            TSVECTOR(),
            sa.Computed("to_tsvector('english', text)", persisted=True),
        ),
        sa.UniqueConstraint("meeting_id", "chunk_index", name="uq_chunks_meeting_index"),
    )

    # Replace the placeholder array column with a real pgvector column. Done as
    # raw SQL because Alembic has no native type for it.
    op.execute("ALTER TABLE chunks DROP COLUMN embedding")
    op.execute(f"ALTER TABLE chunks ADD COLUMN embedding vector({EMBEDDING_DIMENSIONS})")

    op.create_index("ix_chunks_meeting_id", "chunks", ["meeting_id"])
    op.execute("CREATE INDEX ix_chunks_text_search ON chunks USING gin (text_search)")

    # Cosine distance, matching how OpenAI embeddings are normally compared.
    # Cheap to build now on an empty table.
    op.execute(
        "CREATE INDEX ix_chunks_embedding ON chunks USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    op.drop_table("chunks")
    op.drop_table("turns")
    op.drop_table("meetings")
